# _pre-render.R
# Quarto runs this automatically before rendering (via pre-render in _quarto.yml).
# research.xlsx must be in the repo root — it is, since this script lives there too.
# This script reads the xlsx and writes research_data.js which is included by research.qmd.

suppressPackageStartupMessages({
  library(openxlsx)
  library(jsonlite)
})

message("_pre-render.R: reading research.xlsx ...")

tbl <- openxlsx::read.xlsx("research.xlsx")

# Normalise column names
clean <- tolower(trimws(names(tbl)))
clean <- gsub("[^a-z0-9]+", "_", clean)
clean <- gsub("_+", "_", clean)
clean <- gsub("^_|_$", "", clean)

map_name <- function(n) {
  if (grepl("^x$|^x_$|^_$",          n)) return("num")
  if (grepl("topic",                   n)) return("topic")
  if (grepl("reference|^ref",          n)) return("ref")
  if (grepl("oa.type|oa_type|oatype",  n)) return("oatype")
  if (grepl("materials|data",          n)) return("materials")
  if (grepl("preregistration|prereg",  n)) return("prereg")
  if (grepl("pre.print|preprint",      n)) return("preprint")
  if (grepl("student",                 n)) return("student")
  return(n)
}

names(tbl) <- sapply(clean, map_name)

# Ensure all columns exist
for (col in c("num","topic","ref","oatype","materials","prereg","preprint","student")) {
  if (!col %in% names(tbl)) tbl[[col]] <- ""
}

# Use row index as num if blank
if (all(tbl$num == "" | is.na(tbl$num))) tbl$num <- seq_len(nrow(tbl))

tbl[is.na(tbl)] <- ""

out <- data.frame(
  num       = as.character(tbl$num),
  topic     = as.character(tbl$topic),
  ref       = as.character(tbl$ref),
  oatype    = as.character(tbl$oatype),
  materials = as.character(tbl$materials),
  prereg    = as.character(tbl$prereg),
  preprint  = as.character(tbl$preprint),
  student   = as.character(tbl$student),
  stringsAsFactors = FALSE
)

json <- jsonlite::toJSON(out, auto_unbox = TRUE)

js <- paste0("/* Auto-generated by _pre-render.R — do not edit manually */\nvar RT_DATA = ", json, ";\n")

writeLines(js, "research_data.js")

message(sprintf("_pre-render.R: wrote research_data.js with %d rows.", nrow(out)))
