project:
  type: website
  output-dir: docs
  
website:
  title: "Lukas Röseler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - openscience.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/aufdroeseler
      - icon: github
        href: https://github.com/LukasRoeseler/home
  page-footer:
    right: "Built with [Quarto](https://quarto.org/) and [Joyce Robbins' website template](https://github.com/jtr13/website-template)."
    left: "&copy; Copyright 2024, Lukas Röseler"

format:
  html:
    theme: Cosmo
    toc: false

editor: source

