---
title: "Collaborate"
---

Most of the projects that I am contributing to are open to enthusiastic and diligent researchers. Please get in touch if you would like to collaborate.

**Current examples of open projects:**

+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| Project                                                                                                | Description                                                                                                                                                                                   | Tasks                                                             |
+========================================================================================================+===============================================================================================================================================================================================+===================================================================+
| [FORRT Replication Hub](https://forrt.org/replication-hub/)                                            | A collection of projects to support repetitive research across multiple disciplines.                                                                                                          | -   Data curation and validation (volunteer and paid work)        |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Programming of software tools                                 |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Documentation (tutorials, video recordings to facilitate use) |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| [FReD Lighthouse](https://forrt.org/reversals/)                                                        | An educational interface that summarizes replications, reproductions, meta-analyses, and comments/critiques based on central findings.                                                        | -   Data curation and validation (volunteer and paid work)        |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Website creation (concept and coding)                         |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Organization of community meetings to crowdsource data        |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| [Replication Research (R2)](https://www.uni-muenster.de/Ejournals/index.php/replicationresearch/index) | A multidisciplinary, researcher-led, diamond open access journal.                                                                                                                             | -   Editorial assistance (e.g., copy-editing)                     |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Reproducibility checks                                        |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Call for submissions                                          |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Call for editorial members                                    |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| [Open Journal Database](https://metaanalyses.shinyapps.io/openjournals/)                               | Currently, merely a proof of concept that allows researchers to choose a journal for their articles based on more than just intransparent citation metrics such as the journal impact factor. | -   Data wrangling                                                |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Website development (design and programming)                  |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Documentation (tutorial, instructions, scientific article)    |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| Replication Journal Federation                                                                         | We are currently setting up a global network of (open) journals that focus on replication and reproduction studies.                                                                           | -   Administration (e.g., mailing list creation)                  |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Website design                                                |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Member recruitment                                            |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
| [Open Science Book](https://lukasroeseler.github.io/opensciencebuch/)                                  | I am planning to translate my German open science book into English.                                                                                                                          | -   Translation                                                   |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Coding (R, Quarto Markdown, quartobabel package)              |
|                                                                                                        |                                                                                                                                                                                               |                                                                   |
|                                                                                                        |                                                                                                                                                                                               | -   Support in publishing the book at the local library           |
+--------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------+
