<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.53">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Research – Lukas Röseler</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Lukas Röseler</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./research.html" aria-current="page"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./openscience.html"> 
<span class="menu-text">Open Science</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="https://twitter.com/aufdroeseler" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <a href="https://github.com/LukasRoeseler/home" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#open-educational-resources" id="toc-open-educational-resources" class="nav-link active" data-scroll-target="#open-educational-resources">Open educational resources</a></li>
  <li><a href="#research-articles-table" id="toc-research-articles-table" class="nav-link" data-scroll-target="#research-articles-table">Research articles (table)</a></li>
  <li><a href="#research-articles-peer-reviewed" id="toc-research-articles-peer-reviewed" class="nav-link" data-scroll-target="#research-articles-peer-reviewed">Research articles (peer-reviewed)</a></li>
  <li><a href="#research-articles-pre-prints" id="toc-research-articles-pre-prints" class="nav-link" data-scroll-target="#research-articles-pre-prints">Research articles (pre-prints)</a></li>
  <li><a href="#books-and-book-chapters" id="toc-books-and-book-chapters" class="nav-link" data-scroll-target="#books-and-book-chapters">Books and book chapters</a></li>
  <li><a href="#software" id="toc-software" class="nav-link" data-scroll-target="#software">Software</a></li>
  <li><a href="#research-proposals" id="toc-research-proposals" class="nav-link" data-scroll-target="#research-proposals">Research proposals</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Research</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>My research covers Replications, Meta-Science, and Judgment and Decision Making (e.g., Anchoring Effects).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ongoing project: FORRT Replication Database (FReD)
</div>
</div>
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/red_banner_yt.png" class="img-fluid figure-img" width="800"></p>
<figcaption>I am actively working on the <a href="https://forrt-replications.shinyapps.io/fred_explorer/">FORRT Replication Database</a>. Get in touch if you would like to contribute. All materials are stored in the corresponding <a href="https://osf.io/9r62x/">OSF project</a>.</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ongoing project: Interdisciplinary Journal for Replication Research
</div>
</div>
<div class="callout-body-container callout-body">
<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="images/logo3.jpg" class="img-fluid quarto-figure quarto-figure-left figure-img"></p>
</figure>
</div>
<p>Together with an interdisciplinary team of Open Science experts, I am creating a <a href="https://lukasroeseler.github.io/replicationresearch_mockup/">publication platform for replication research</a>. Get in touch if you seek for ways to publish replication research or if you want to help making replications mainstream.</p>
</div>
</div>
<section id="open-educational-resources" class="level1">
<h1>Open educational resources</h1>
<ul>
<li><p>I have been writing a <a href="lukasroeseler.github.io/opensciencebuch/">German book on Open Science, which is available online</a>.</p></li>
<li><p>I upload most slides and materials from my workshops, lectures, talks, and seminars to this OSF repository: <a href="#0" class="uri">https://osf.io/at29b/</a></p></li>
<li><p>Together with experts from the University of Münster’s psychology open science commission, I have been preparing an interdisciplinary guide to Open Science (German, WIP): <a href="https://lukasroeseler.github.io/MueCOS-Infomodule/" class="uri">https://lukasroeseler.github.io/MueCOS-Infomodule/</a></p></li>
</ul>
</section>
<section id="research-articles-table" class="level1">
<h1>Research articles (table)</h1>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Reference</th>
<th>OSF-Link</th>
<th>Preregistration</th>
<th>Pre-Print</th>
<th>Journal publication</th>
<th>Diamond Open Access?</th>
<th>Student collaboration?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Bögler, H. L., Koßmann, L., Krueger, S., Bickenbach, S., Bühler, R., … Sing, J. (in press). Replicating Epley and Gilovich: Need for Cognition, Cognitive Load, and Forewarning do not Moderate Anchoring Effects. <em>Journal of Comments and Replications in Economics</em>. <a href="https://doi.org/10.31234/osf.io/bgp3m" class="uri">https://doi.org/10.31234/osf.io/bgp3m</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
<td>yes</td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Weber, L., Stich, E., Helgerth, K., Günther, M., Wagner, F.-S., &amp; Schütz, A. (in press). Measurements of Susceptibility to Anchoring are Unreliable: Meta-Analytic Evidence From More Than 50,000 Anchored Estimates. <em>Meta Psychology.</em> <a href="https://doi.org/10.31234/osf.io/b6t35" class="uri">https://doi.org/10.31234/osf.io/b6t35</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Kaiser, L., Doetsch, C., Klett, N., Seida, C., Schütz, A., Aczel, B., Adelina, N., Agostini, V., Alarie, S., Albayrak-Aydemir, N., Aldoh, A., Al-Hoorie, A. H., Azevedo, F., Baker, B. J., Barth, C. L., Beitner, J., Brick, C., Brohmer, H., Chandrashekar, S. P., Chung, K. L., Cockcroft, J. P., Cummins, J., Diveica, V., Dumbalska, T., Efendic, E., Elsherif, M., Evans, T., Feldman, G., Fillon, A., Förster, N., Frese, J., Genschow, O., Giannouli, V., Gjoneska, B., Gnambs, T., Gourdon-Kanhukamwe, A., Graham, C. J., Hartmann, H., Haviva, C., Herderich, A., Hilbert, L. P., Holgado, D., Hussey, I., Ilchovska, Z. G., Kalandadze, T., Karhulahti, V.-M., Kasseckert, L., Klingelhöfer-Jens, M., Koppold, A., Korbmacher, M., Kulke, L., Kuper, N., LaPlume, A., Leech, G., Lohkamp, F., Lou, N. M., Lynott, D., Maier, M., Meier, M., Montefinese, M., Moreau, D., Mrkva, K., Nemcova, M., Oomen, D., Packheiser, J., Pandey, S., Papenmeier, F., Paruzel-Czachura, M., Pavlov, Y. G., Pavlović, Z., Pennington, C. R., Pittelkow, M.-M., Plomp, W., Plonski, P. E., Pronizius, E., Pua, A. A., Pypno-Blajda, K., Rausch, M., Rebholz, T. R., Richert, E., Röer, J. P., Ross, R., Schmidt, K., Skvortsova, A., Sperl, M. F. J., Tan, A. W. M., Thürmer, J. L., Tołopiło, A., Vanpaemel, W., Vaughn, L. A., Verheyen, S., Wallrich, L., Weber, L., Wolska, J. K., Zaneva, M., &amp; Zhang, Y. (2024). The Replication Database: Documenting the Replicability of Psychological Science.<br>
<em>Journal of Open Psychology Data,</em> 12: 8, pp.&nbsp;1–23. DOI:&nbsp;<a href="https://doi.org/10.5334/jopd.101" class="uri">https://doi.org/10.5334/jopd.101</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Felser, G., Asberger, J., &amp; Schütz, A. (2024). The Effect of Variety on Perceived Quantity: Failures to Replicate Redden and Hoch (2009). Meta-Psychology, 8. <a href="https://doi.org/10.15626/MP.2020.2639" class="uri">https://doi.org/10.15626/MP.2020.2639</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Weber, L., Helgerth, K., Stich, E., Günther, M., Tegethoff, P., Wagner, F. S., Ambrus, E., Antunovic, M., Barrera-Lemarchand, F., Halali, E., Ioannidis, K., Genschow, O., McKay, R., Milstein, N., Molden, D. C., Papenmeier, F., Pavlovic, Z., Rinn, R., Schreiter, M. L., Zimdahl, M. F., Allen, E., Bahník, Š., Bermeitinger, C., Blower, F. B. N., Bögler, H. L., Burgmer, P., Cheek, N. N., Dorsch, L., Fels, S. A., Frech, M.-L., Freira, L., Harris, A. J. L., Hartig, B., Häusser, J. A., Hedgebeth, M. V., Henkel, M., Horvath, D., Imhoff, R., Intelmann, P., Klamar, A., Knappe, E., Köppel, L.-M., Krueger, S. M., Lagator, S., López Bóo, F., Navajas, J., Norem, J. K., Novak, J., Onuki, Y., Page, E., Pearton, J., Ponader, S., Rebholz, T. R., Rostekova, A., Sartorio, M., Schindler, S., Seida, C., Shanks, D. R., Siems, M.-C., Speekenbrink, M., Stäglich, P., Starkulla, M., Stitz, M., Straube, T., Thies, K., Thum, E., Ueda, K., Undorf, M., Urlichich, D., Vadillo, M. A., Wolf, H., Zhou, A., &amp; Schütz, A. (2024). Correction: The Open Anchoring Quest Dataset: Anchored Estimates from 96 Studies on Anchoring Effects. <em>Journal of Open Psychology Data,</em> 12: 8, pp.&nbsp;1–3. <a href="https://doi.org/10.5334/jopd.92" class="uri">https://doi.org/10.5334/jopd.92</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="even">
<td>Adler, S. J., <strong>Röseler, L.</strong>, &amp; Schöniger, M. K. (2023). A toolbox to evaluate the trustworthiness of published findings. <em>Journal of Business Research</em>, <em>167</em>, 114189. <a href="https://doi.org/10.1016/j.jbusres.2023.114189" class="uri">https://doi.org/10.1016/j.jbusres.2023.114189</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Weber, L., Helgerth, K., Stich, E., Günther, M., Tegethoff, P., Wagner, F., Antunovic, M., BarreraLemarchand, F., Halali, E., Ioannidis, K., Genschow, O., Milstein, N., Molden, D. C., Papenmeier, F., Pavlovic, Z., Rinn, R., Schreiter, M. L., Zimdahl, M. F., Bahník, Š., Bermeitinger, C., Blower, F. B. N., Bögler, H. L., Burgmer, P., Cheek, N. N., Dorsch, L., Fels, S., Frech, M.-L., Freira, L., Harris, A. J. L., Häusser, J. A., Hedgebeth, M. V., Henkel, M., Horvath, D., Intelmann, P., Klamar, A., Knappe, E., Köppel, L.-M., Krueger, S. M., Lagator, S., Lopez-Boo, F., Navajas, J., Norem, J. K., Novak, J., Onuki, Y., Page, E., Rebholz, T. R., Sartorio, M., Schindler, S., Shanks, D. R., Siems, M.-C., Stäglich, P., Starkulla, M., Stitz, M., Straube, T., Thies, K., Thum, E., Ueda, K., Undorf, M., Urlichich, D., Vadillo, M. A., Wolf, H., Zhou, A., &amp; Schütz, A. (2022). The Open Anchoring Quest Dataset: Anchored Estimates from 96 Studies on Anchoring Effects. <em>Journal of Open Psychology Data, 10</em>(16), pp.&nbsp;1–12. <a href="http://doi.org/10.5334/jopd.67" class="uri">http://doi.org/10.5334/jopd.67</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="even">
<td>Delios, A., Clemente, E., Wu, T., Tan, H., Wang, Y., Gordon, M., Viganola, D., Chen, Z., Dreber, A., Johannesson, M., Pfeiffer, T., <strong>Generalizability Tests Forecasting Collaboration</strong>, &amp; Uhlmann, E.L. (2022). Examining the context sensitivity of research findings from archival data. <em>Proceedings of the National Academy of Sciences</em>. <a href="https://doi.org/10.1073/pnas.212037711" class="uri">https://doi.org/10.1073/pnas.212037711</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Körner*, R., <strong>Röseler*, L.</strong>, Schütz, A., &amp; Bushman, B. J. (2022). Dominance and prestige: Meta-analytic review of experimentally induced body position effects on behavioral, self-report, and physiological dependent variables.<em>Psychological Bulletin, 148</em>(1-2), 67–85. <a href="https://doi.org/10.1037/bul0000356" class="uri">https://doi.org/10.1037/bul0000356</a> *shared first authorship</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Wolf, D., Leder, J., <strong>Röseler, L.</strong>, &amp; Schütz, A. (2021). Does Facial Redness Really Affect Emotion Perception? Evidence for Limited Generalisability of Effects of Facial Redness on Emotion Perception in a Large Sample. <em>Cognition and Emotion</em>. 35(8), 1607–1617. <a href="https://doi.org/10.1080/02699931.2021.1979473" class="uri">https://doi.org/10.1080/02699931.2021.1979473</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Schütz, A., Blank, P. A., Dück, M., Fels, S., Kupfer, J., Scheelje, L., &amp; Seida, C. (2021). Evidence against subliminal anchoring: Two close, highly powered, preregistered, and failed replication attempts. <em>Journal of Experimental Social Psychology</em>, <em>92</em>, 104066. <a href="https://doi.org/10.1016/j.jesp.2020.104066" class="uri">https://doi.org/10.1016/j.jesp.2020.104066</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Ebert, J., Schütz, A., &amp; Baumeister, R. F. (2021). The upsides and downsides of high self-control: Evidence for effects of similarity and situation dependency. <em>Europe’s Journal of Psychology</em>, <em>17</em>(1), 1–16. <a href="https://doi.org/10.5964/ejop.2639" class="uri">https://doi.org/10.5964/ejop.2639</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td>Körner, R., <strong>Röseler, L.</strong>, &amp; Schütz, A. (2021). Commentary on Elkjær et al.’s (2020) meta-analysis on expansive versus contractive nonverbal displays.<em>Perspectives on Psychological Science, 17</em>(1), 305–307. <a href="https://doi.org/10.1177/1745691620984474" class="uri">https://doi.org/10.1177/1745691620984474</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Tierney, W., Hardy, J. H., III., Ebersole, C., Viganola, D., Clemente, E., Gordon, M., Hoogeveen, S., Haaf, J., Dreber, A.A., Johannesson, M., Pfeiffer, T., Chapman, H., Gantman, A., Vanaman, M., DeMarree, K., Igou, E., Wylie, J., Storbeck J., Andreychik, M.R., McPhetres, J., Vaughn, L.A., … <strong>Röseler, L.,</strong> …Uhlmann, E. L.(2021). A creative destruction approach to replication: Implicit work and sex morality across cultures. <em>Journal of Experimental Social Psychology, 93,</em> 104060. <a href="https://doi.org/10.1016/j.jesp.2020.104060" class="uri">https://doi.org/10.1016/j.jesp.2020.104060</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Schütz, A., Baumeister, R. F., &amp; Starker, U. (2020). Does ego depletion reduce judgment adjustment for both internally and externally generated anchors? <em>Journal of Experimental Social Psychology</em>, <em>87</em>, 103942. <a href="https://doi.org/10.1016/j.jesp.2019.103942" class="uri">https://doi.org/10.1016/j.jesp.2019.103942</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Landy, J. F., Jia, M. L., Ding, I. L., Viganola, D., Tierney, W., Dreber, A., Johannesson, M., Pfeiffer, T., Ebersole, C. R., Gronau, Q. F., Ly, A., van den Bergh, D., Marsman, M., Derks, K., Wagenmakers, E.-J., Proctor, A., Bartels, D. M., Bauman, C. W., Brady, W. J.,... <strong>Röseler, L.</strong>, … Uhlmann, E. L. (2020). Crowdsourcing hypothesis tests: Making transparent how design choices shape research results. <em>Psychological Bulletin</em>, <em>146</em>(5), 451–479. <a href="https://doi.org/10.1037/bul0000220" class="uri">https://doi.org/10.1037/bul0000220</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong> (2020, September). <em>Anchoring Effects: Resolving the Contradictions of Personality Moderator Research (Doctoral Thesis)</em>. University of Bamberg. <a href="https://osf.io/34sv6" class="uri">https://osf.io/34sv6</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>peer reviewed</td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Doetsch, C. A., Förster, N., Bruzsa, A., Deublein, M., Rieger, E., Schmidt, C., Seitz, A., &amp;Wild, A. (2024). No Evidence for the Affective Expectation Model: Replication of Geers and Lassiter (2003). <a href="https://doi.org/10.31234/osf.io/akfzh" class="uri">https://doi.org/10.31234/osf.io/akfzh</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong> (2024). Exploring Categorical Colors. <a href="https://doi.org/10.31234/osf.io/gj76p" class="uri">https://doi.org/10.31234/osf.io/gj76p</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, &amp; Schütz, A. (2024). Assimilation and Contrast are Everywhere. <a href="https://doi.org/10.31234/osf.io/krwcn" class="uri">https://doi.org/10.31234/osf.io/krwcn</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong> (2023). <em>Predicting Replication Rates with Z-Curve: A Brief Exploratory Validation Study Using the Replication Database</em>. Advance online publication. <a href="https://osf.io/preprints/metaarxiv/ewb2t" class="uri">https://osf.io/preprints/metaarxiv/ewb2t</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Incerti, L., Seida, C., Rebholz, T., Papenmeier, F. (2023). <em>Falsifying the Insufficient Adjustment Model: No Evidence for Unidirectional Adjustment From Anchors</em>. Advance online publication. <a href="https://osf.io/8cwpy" class="uri">https://osf.io/8cwpy</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Gendlina, T., Krapp, J., Labusch, N., &amp; Schütz, A. (2022). Successes and Failures of Replications: A Meta-Analysis of Independent Replication Studies Based on the OSF Registries. Advance online publication. <a href="https://doi.org/10.31222/osf.io/8psw2" class="uri">https://doi.org/10.31222/osf.io/8psw2</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="even">
<td>Weber, L., &amp; <strong>Röseler, L.</strong> (2022). Testing the Reliability of Anchoring Susceptibility Scores. Advance online publication. <a href="https://doi.org/10.31234/osf.io/2kfh3" class="uri">https://doi.org/10.31234/osf.io/2kfh3</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td>Wolf, D., <strong>Röseler, L.</strong>, Leder, J., &amp; Schütz, A. (2022). The Red-Anger Effect: Is it Nothing More Than Demand Characteristics? Advance online publication. <a href="https://doi.org/10.31234/osf.io/ntukz" class="uri">https://doi.org/10.31234/osf.io/ntukz</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, &amp; Schütz, A. (2022). Hanging the Anchor Off a New Ship: A Meta-Analysis of Anchoring Effects. <a href="https://doi.org/10.31234/osf.io/wf2tn" class="uri">https://doi.org/10.31234/osf.io/wf2tn</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Schütz, A. (2021). What You Expect is What You Get: The Role of Affective Expectations in Real-World Experiences. <a href="https://doi.org/10.31219/osf.io/2tr6q" class="uri">https://doi.org/10.31219/osf.io/2tr6q</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Schütz, A., Dolling, I. K., Friedinger, K., Hösch, Y., Hügel, J. C., Igna, E., Karg, A., Kühling, S., Schäffer, D., Zhou, A., &amp; Röseler, J. J. (2020). The Stepwise Anchoring Paradigm: Measuring Reliable Components of Anchoring and Adjustment as the Next Step in Moderator Research. <a href="https://doi.org/10.31234/osf.io/hjbwp" class="uri">https://doi.org/10.31234/osf.io/hjbwp</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td>yes</td>
</tr>
<tr class="odd">
<td><strong>Röseler, L.</strong>, Wolf, D., Leder, J., &amp; Schütz, A. (2020). Test-Retest Reliability is not a Measure of Reliability or Stability: A Friendly Reminder. <a href="https://doi.org/10.31234/osf.io/mt49r" class="uri">https://doi.org/10.31234/osf.io/mt49r</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><strong>Röseler, L.</strong>, Schütz, A., &amp; Starker, U. (2019). Cognitive Ability does not and cannot Correlate with Susceptibility to Anchoring Effects. <a href="https://doi.org/10.31234/osf.io/bnsx2" class="uri">https://doi.org/10.31234/osf.io/bnsx2</a></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="research-articles-peer-reviewed" class="level1">
<h1>Research articles (peer-reviewed)</h1>
<ul>
<li><p><strong>Röseler, L.</strong>, Bögler, H. L., Koßmann, L., Krueger, S., Bickenbach, S., Bühler, R., … Sing, J. (in press). Replicating Epley and Gilovich: Need for Cognition, Cognitive Load, and Forewarning do not Moderate Anchoring Effects. <em>Journal of Comments and Replications in Economics</em>. <a href="https://doi.org/10.31234/osf.io/bgp3m" class="uri">https://doi.org/10.31234/osf.io/bgp3m</a></p></li>
<li><p><strong>Röseler, L.</strong>, Weber, L., Stich, E., Helgerth, K., Günther, M., Wagner, F.-S., &amp; Schütz, A. (in press). Measurements of Susceptibility to Anchoring are Unreliable: Meta-Analytic Evidence From More Than 50,000 Anchored Estimates. <em>Meta Psychology.</em> <a href="https://doi.org/10.31234/osf.io/b6t35" class="uri">https://doi.org/10.31234/osf.io/b6t35</a></p></li>
<li><p><strong>Röseler, L.</strong>, Kaiser, L., Doetsch, C., Klett, N., Seida, C., Schütz, A., Aczel, B., Adelina, N., Agostini, V., Alarie, S., Albayrak-Aydemir, N., Aldoh, A., Al-Hoorie, A. H., Azevedo, F., Baker, B. J., Barth, C. L., Beitner, J., Brick, C., Brohmer, H., Chandrashekar, S. P., Chung, K. L., Cockcroft, J. P., Cummins, J., Diveica, V., Dumbalska, T., Efendic, E., Elsherif, M., Evans, T., Feldman, G., Fillon, A., Förster, N., Frese, J., Genschow, O., Giannouli, V., Gjoneska, B., Gnambs, T., Gourdon-Kanhukamwe, A., Graham, C. J., Hartmann, H., Haviva, C., Herderich, A., Hilbert, L. P., Holgado, D., Hussey, I., Ilchovska, Z. G., Kalandadze, T., Karhulahti, V.-M., Kasseckert, L., Klingelhöfer-Jens, M., Koppold, A., Korbmacher, M., Kulke, L., Kuper, N., LaPlume, A., Leech, G., Lohkamp, F., Lou, N. M., Lynott, D., Maier, M., Meier, M., Montefinese, M., Moreau, D., Mrkva, K., Nemcova, M., Oomen, D., Packheiser, J., Pandey, S., Papenmeier, F., Paruzel-Czachura, M., Pavlov, Y. G., Pavlović, Z., Pennington, C. R., Pittelkow, M.-M., Plomp, W., Plonski, P. E., Pronizius, E., Pua, A. A., Pypno-Blajda, K., Rausch, M., Rebholz, T. R., Richert, E., Röer, J. P., Ross, R., Schmidt, K., Skvortsova, A., Sperl, M. F. J., Tan, A. W. M., Thürmer, J. L., Tołopiło, A., Vanpaemel, W., Vaughn, L. A., Verheyen, S., Wallrich, L., Weber, L., Wolska, J. K., Zaneva, M., &amp; Zhang, Y. (2024). The Replication Database: Documenting the Replicability of Psychological Science.<br>
<em>Journal of Open Psychology Data,</em> 12: 8, pp.&nbsp;1–23. DOI:&nbsp;<a href="https://doi.org/10.5334/jopd.101" class="uri">https://doi.org/10.5334/jopd.101</a></p></li>
<li><p><strong>Röseler, L.</strong>, Felser, G., Asberger, J., &amp; Schütz, A. (2024). The Effect of Variety on Perceived Quantity: Failures to Replicate Redden and Hoch (2009). Meta-Psychology, 8. <a href="https://doi.org/10.15626/MP.2020.2639" class="uri">https://doi.org/10.15626/MP.2020.2639</a></p></li>
<li><p><strong>Röseler, L.</strong>, Weber, L., Helgerth, K., Stich, E., Günther, M., Tegethoff, P., Wagner, F. S., Ambrus, E., Antunovic, M., Barrera-Lemarchand, F., Halali, E., Ioannidis, K., Genschow, O., McKay, R., Milstein, N., Molden, D. C., Papenmeier, F., Pavlovic, Z., Rinn, R., Schreiter, M. L., Zimdahl, M. F., Allen, E., Bahník, Š., Bermeitinger, C., Blower, F. B. N., Bögler, H. L., Burgmer, P., Cheek, N. N., Dorsch, L., Fels, S. A., Frech, M.-L., Freira, L., Harris, A. J. L., Hartig, B., Häusser, J. A., Hedgebeth, M. V., Henkel, M., Horvath, D., Imhoff, R., Intelmann, P., Klamar, A., Knappe, E., Köppel, L.-M., Krueger, S. M., Lagator, S., López Bóo, F., Navajas, J., Norem, J. K., Novak, J., Onuki, Y., Page, E., Pearton, J., Ponader, S., Rebholz, T. R., Rostekova, A., Sartorio, M., Schindler, S., Seida, C., Shanks, D. R., Siems, M.-C., Speekenbrink, M., Stäglich, P., Starkulla, M., Stitz, M., Straube, T., Thies, K., Thum, E., Ueda, K., Undorf, M., Urlichich, D., Vadillo, M. A., Wolf, H., Zhou, A., &amp; Schütz, A. (2024). Correction: The Open Anchoring Quest Dataset: Anchored Estimates from 96 Studies on Anchoring Effects. <em>Journal of Open Psychology Data,</em> 12: 8, pp.&nbsp;1–3. <a href="https://doi.org/10.5334/jopd.92" class="uri">https://doi.org/10.5334/jopd.92</a></p></li>
<li><p>Adler, S. J., <strong>Röseler, L.</strong>, &amp; Schöniger, M. K. (2023). A toolbox to evaluate the trustworthiness of published findings. <em>Journal of Business Research</em>, <em>167</em>, 114189. <a href="https://doi.org/10.1016/j.jbusres.2023.114189" class="uri">https://doi.org/10.1016/j.jbusres.2023.114189</a></p></li>
<li><p><strong>Röseler, L.</strong>, Weber, L., Helgerth, K., Stich, E., Günther, M., Tegethoff, P., Wagner, F., Antunovic, M., BarreraLemarchand, F., Halali, E., Ioannidis, K., Genschow, O., Milstein, N., Molden, D. C., Papenmeier, F., Pavlovic, Z., Rinn, R., Schreiter, M. L., Zimdahl, M. F., Bahník, Š., Bermeitinger, C., Blower, F. B. N., Bögler, H. L., Burgmer, P., Cheek, N. N., Dorsch, L., Fels, S., Frech, M.-L., Freira, L., Harris, A. J. L., Häusser, J. A., Hedgebeth, M. V., Henkel, M., Horvath, D., Intelmann, P., Klamar, A., Knappe, E., Köppel, L.-M., Krueger, S. M., Lagator, S., Lopez-Boo, F., Navajas, J., Norem, J. K., Novak, J., Onuki, Y., Page, E., Rebholz, T. R., Sartorio, M., Schindler, S., Shanks, D. R., Siems, M.-C., Stäglich, P., Starkulla, M., Stitz, M., Straube, T., Thies, K., Thum, E., Ueda, K., Undorf, M., Urlichich, D., Vadillo, M. A., Wolf, H., Zhou, A., &amp; Schütz, A. (2022). The Open Anchoring Quest Dataset: Anchored Estimates from 96 Studies on Anchoring Effects. <em>Journal of Open Psychology Data, 10</em>(16), pp.&nbsp;1–12. <a href="http://doi.org/10.5334/jopd.67" class="uri">http://doi.org/10.5334/jopd.67</a></p></li>
<li><p>Delios, A., Clemente, E., Wu, T., Tan, H., Wang, Y., Gordon, M., Viganola, D., Chen, Z., Dreber, A., Johannesson, M., Pfeiffer, T., <strong>Generalizability Tests Forecasting Collaboration</strong>, &amp; Uhlmann, E.L. (2022). Examining the context sensitivity of research findings from archival data. <em>Proceedings of the National Academy of Sciences</em>. <a href="https://doi.org/10.1073/pnas.212037711" class="uri">https://doi.org/10.1073/pnas.212037711</a></p></li>
<li><p>Körner*, R., <strong>Röseler*, L.</strong>, Schütz, A., &amp; Bushman, B. J. (2022). Dominance and prestige: Meta-analytic review of experimentally induced body position effects on behavioral, self-report, and physiological dependent variables.<em>Psychological Bulletin, 148</em>(1-2), 67–85. <a href="https://doi.org/10.1037/bul0000356" class="uri">https://doi.org/10.1037/bul0000356</a> *shared first authorship</p></li>
<li><p>Wolf, D., Leder, J., <strong>Röseler, L.</strong>, &amp; Schütz, A. (2021). Does Facial Redness Really Affect Emotion Perception? Evidence for Limited Generalisability of Effects of Facial Redness on Emotion Perception in a Large Sample. <em>Cognition and Emotion</em>. 35(8), 1607–1617. <a href="https://doi.org/10.1080/02699931.2021.1979473" class="uri">https://doi.org/10.1080/02699931.2021.1979473</a></p></li>
<li><p><strong>Röseler, L.</strong>, Schütz, A., Blank, P. A., Dück, M., Fels, S., Kupfer, J., Scheelje, L., &amp; Seida, C. (2021). Evidence against subliminal anchoring: Two close, highly powered, preregistered, and failed replication attempts. <em>Journal of Experimental Social Psychology</em>, <em>92</em>, 104066. <a href="https://doi.org/10.1016/j.jesp.2020.104066" class="uri">https://doi.org/10.1016/j.jesp.2020.104066</a></p></li>
<li><p><strong>Röseler, L.</strong>, Ebert, J., Schütz, A., &amp; Baumeister, R. F. (2021). The upsides and downsides of high self-control: Evidence for effects of similarity and situation dependency. <em>Europe’s Journal of Psychology</em>, <em>17</em>(1), 1–16. <a href="https://doi.org/10.5964/ejop.2639" class="uri">https://doi.org/10.5964/ejop.2639</a></p></li>
<li><p>Körner, R., <strong>Röseler, L.</strong>, &amp; Schütz, A. (2021). Commentary on Elkjær et al.’s (2020) meta-analysis on expansive versus contractive nonverbal displays.<em>Perspectives on Psychological Science, 17</em>(1), 305–307. <a href="https://doi.org/10.1177/1745691620984474" class="uri">https://doi.org/10.1177/1745691620984474</a></p></li>
<li><p>Tierney, W., Hardy, J. H., III., Ebersole, C., Viganola, D., Clemente, E., Gordon, M., Hoogeveen, S., Haaf, J., Dreber, A.A., Johannesson, M., Pfeiffer, T., Chapman, H., Gantman, A., Vanaman, M., DeMarree, K., Igou, E., Wylie, J., Storbeck J., Andreychik, M.R., McPhetres, J., Vaughn, L.A., … <strong>Röseler, L.,</strong> …Uhlmann, E. L.(2021). A creative destruction approach to replication: Implicit work and sex morality across cultures. <em>Journal of Experimental Social Psychology, 93,</em> 104060. <a href="https://doi.org/10.1016/j.jesp.2020.104060" class="uri">https://doi.org/10.1016/j.jesp.2020.104060</a></p></li>
<li><p><strong>Röseler, L.</strong>, Schütz, A., Baumeister, R. F., &amp; Starker, U. (2020). Does ego depletion reduce judgment adjustment for both internally and externally generated anchors? <em>Journal of Experimental Social Psychology</em>, <em>87</em>, 103942. <a href="https://doi.org/10.1016/j.jesp.2019.103942" class="uri">https://doi.org/10.1016/j.jesp.2019.103942</a></p></li>
<li><p>Landy, J. F., Jia, M. L., Ding, I. L., Viganola, D., Tierney, W., Dreber, A., Johannesson, M., Pfeiffer, T., Ebersole, C. R., Gronau, Q. F., Ly, A., van den Bergh, D., Marsman, M., Derks, K., Wagenmakers, E.-J., Proctor, A., Bartels, D. M., Bauman, C. W., Brady, W. J.,... <strong>Röseler, L.</strong>, … Uhlmann, E. L. (2020). Crowdsourcing hypothesis tests: Making transparent how design choices shape research results. <em>Psychological Bulletin</em>, <em>146</em>(5), 451–479. <a href="https://doi.org/10.1037/bul0000220" class="uri">https://doi.org/10.1037/bul0000220</a></p></li>
<li><p><strong>Röseler, L.</strong> (2020, September). <em>Anchoring Effects: Resolving the Contradictions of Personality Moderator Research (Doctoral Thesis)</em>. University of Bamberg. <a href="https://osf.io/34sv6" class="uri">https://osf.io/34sv6</a></p></li>
</ul>
</section>
<section id="research-articles-pre-prints" class="level1">
<h1>Research articles (pre-prints)</h1>
<ul>
<li><p><strong>Röseler, L.</strong>, Doetsch, C. A., Förster, N., Bruzsa, A., Deublein, M., Rieger, E., Schmidt, C., Seitz, A., &amp;Wild, A. (2024). No Evidence for the Affective Expectation Model: Replication of Geers and Lassiter (2003). <a href="https://doi.org/10.31234/osf.io/akfzh" class="uri">https://doi.org/10.31234/osf.io/akfzh</a></p></li>
<li><p><strong>Röseler, L.</strong> (2024). Exploring Categorical Colors. <a href="https://doi.org/10.31234/osf.io/gj76p" class="uri">https://doi.org/10.31234/osf.io/gj76p</a></p></li>
<li><p><strong>Röseler, L.</strong>, &amp; Schütz, A. (2024). Assimilation and Contrast are Everywhere. <a href="https://doi.org/10.31234/osf.io/krwcn" class="uri">https://doi.org/10.31234/osf.io/krwcn</a></p></li>
<li><p><strong>Röseler, L.</strong> (2023). <em>Predicting Replication Rates with Z-Curve: A Brief Exploratory Validation Study Using the Replication Database</em>. Advance online publication. <a href="https://osf.io/preprints/metaarxiv/ewb2t" class="uri">https://osf.io/preprints/metaarxiv/ewb2t</a></p></li>
<li><p><strong>Röseler, L.</strong>, Incerti, L., Seida, C., Rebholz, T., Papenmeier, F. (2023). <em>Falsifying the Insufficient Adjustment Model: No Evidence for Unidirectional Adjustment From Anchors</em>. Advance online publication. <a href="https://osf.io/8cwpy" class="uri">https://osf.io/8cwpy</a></p></li>
<li><p><strong>Röseler, L.</strong>, Gendlina, T., Krapp, J., Labusch, N., &amp; Schütz, A. (2022). Successes and Failures of Replications: A Meta-Analysis of Independent Replication Studies Based on the OSF Registries. Advance online publication. <a href="https://doi.org/10.31222/osf.io/8psw2" class="uri">https://doi.org/10.31222/osf.io/8psw2</a></p></li>
<li><p>Weber, L., &amp; <strong>Röseler, L.</strong> (2022). Testing the Reliability of Anchoring Susceptibility Scores. Advance online publication. <a href="https://doi.org/10.31234/osf.io/2kfh3" class="uri">https://doi.org/10.31234/osf.io/2kfh3</a></p></li>
<li><p>Wolf, D., <strong>Röseler, L.</strong>, Leder, J., &amp; Schütz, A. (2022). The Red-Anger Effect: Is it Nothing More Than Demand Characteristics? Advance online publication. <a href="https://doi.org/10.31234/osf.io/ntukz" class="uri">https://doi.org/10.31234/osf.io/ntukz</a></p></li>
<li><p><strong>Röseler, L.</strong>, &amp; Schütz, A. (2022). Hanging the Anchor Off a New Ship: A Meta-Analysis of Anchoring Effects. <a href="https://doi.org/10.31234/osf.io/wf2tn" class="uri">https://doi.org/10.31234/osf.io/wf2tn</a></p></li>
<li><p><strong>Röseler, L.</strong>, Schütz, A. (2021). What You Expect is What You Get: The Role of Affective Expectations in Real-World Experiences. <a href="https://doi.org/10.31219/osf.io/2tr6q" class="uri">https://doi.org/10.31219/osf.io/2tr6q</a></p></li>
<li><p><strong>Röseler, L.</strong>, Schütz, A., Dolling, I. K., Friedinger, K., Hösch, Y., Hügel, J. C., Igna, E., Karg, A., Kühling, S., Schäffer, D., Zhou, A., &amp; Röseler, J. J. (2020). The Stepwise Anchoring Paradigm: Measuring Reliable Components of Anchoring and Adjustment as the Next Step in Moderator Research. <a href="https://doi.org/10.31234/osf.io/hjbwp" class="uri">https://doi.org/10.31234/osf.io/hjbwp</a></p></li>
<li><p><strong>Röseler, L.</strong>, Wolf, D., Leder, J., &amp; Schütz, A. (2020). Test-Retest Reliability is not a Measure of Reliability or Stability: A Friendly Reminder. <a href="https://doi.org/10.31234/osf.io/mt49r" class="uri">https://doi.org/10.31234/osf.io/mt49r</a></p></li>
<li><p><strong>Röseler, L.</strong>, Schütz, A., &amp; Starker, U. (2019). Cognitive Ability does not and cannot Correlate with Susceptibility to Anchoring Effects. <a href="https://doi.org/10.31234/osf.io/bnsx2" class="uri">https://doi.org/10.31234/osf.io/bnsx2</a></p></li>
</ul>
</section>
<section id="books-and-book-chapters" class="level1">
<h1>Books and book chapters</h1>
<ul>
<li><p><strong>Röseler, L.</strong> (in preparation). Open Science: Wie sich die Wissenschaft öffnet (0.1th ed.). https://doi.org/10.17605/OSF.IO/2QXWV</p></li>
<li><p>Jané, M., Xiao, Q., Yeung, S., Ben-Shachar, M. S., Caldwell, A., Cousineau, D., ... <strong>Röseler, L.</strong>, … &amp; Feldman, G. (2024). Guide to Effect Sizes and Confidence Intervals. <a href="http://dx.doi.org/10.17605/OSF.IO/D8C4G" class="uri">http://dx.doi.org/10.17605/OSF.IO/D8C4G</a></p></li>
<li><p><strong>Röseler, L.</strong>, &amp; Schütz, A. (2022). Open Science. In A. Schütz, M. Brand, S. Steins-Loeber, (Eds.), <em>Psychologie: Eine Einführung in ihre Grundlagen und Anwendungsfelder</em> (6th ed., pp.&nbsp;187–198). Kohlhammer.</p></li>
</ul>
</section>
<section id="software" class="level1">
<h1>Software</h1>
<ul>
<li><p><strong>Röseler, L.</strong>, Wallrich, L. (2024).&nbsp;<em>FReD: Interfaces to the FORRT Replication Database</em>. R package version 0.0.0.9001,&nbsp;<a href="http://forrt.org/FReD/" class="uri">http://forrt.org/FReD/</a>.</p></li>
<li><p><strong>Röseler, L.</strong>, Kaiser, L., Doetsch, C., Weber, L., Klett, N., Krapp, J., Seida, C., Schütz, A., Barth, C., Cummins, J., Dienlin, T., Elsherif, M., Förster, N., Genschow, O., Gnambs, T., Hartmann, H., Hilbert, L., Holgado, D., Hussey, I., Korbmacher, M., Kulke, L., Liu, Y., Lohkamp, F., Lou, N., Oomen, D., Papenmeier, F., Paruzel-Czachura, M., Pavlov, Y., Pavlović, Z., Pypno, K., Rausch, M., Rebholz, T., Ross, R., Sperl, M., Thürmer, L., Vaughn, L., Zaneva, M. (2024).<em>ReD: Replication Database, Version 0.4.22</em>.<a href="https://dx.doi.org/10.17605/OSF.IO/9r62x" class="uri">https://dx.doi.org/10.17605/OSF.IO/9r62x</a></p></li>
<li><p><strong>Röseler, L.</strong>, Weber, L., Stich, E., Günther, M., Helgerth, K. A. C., Wagner, F. S., Antunovic, M., Bahník, S., Barrera, F., Baumeister, R. F., Bermeitinger, C., Bickenbach, S. L. C., Blank, P. A., Blower, F. B. N., Bögler, H. L., Boo, F. L., Boruchowicz, C., Bühler, R. L., Burgmer, P., Cheek, N., N., Dohle, S., Dorsch, L., Dück, M. S., Halali, E.., Fels, S.-A., Fischer, A. L., Frech, M.-L., Freira, L., Friedinger, K., Genschow, O., Harris, A., Häusser, J. A., Hedgebeth, M., Henkel, M., Horvath, D., Hügel, J. C., Igna, E. L. E., Imhoff, R., Intelmann, P., Ioannidis, K., Karg, A. H., Klamar, A., Klein, C., Klusmann, B., Knappe, E., Köppel, L.-M., Koßmann, L., Kraft, P., Kroworsch, M. K., Krueger, S. M., Kühling, S., Lagator, S., Lammers, J., Loschelder, D. D., Milstein, N., Molden, D. C., Navajas, J., Norem, J., K., Novak, J. Onuki, Y., Page, E., Panse, F., Papenmeier, F., Pavlovic, Z., Rebholz, T. R., Rinn, R., Rodgers, S., Röseler, J. J., Roßmaier, K. V., Sartorio, M., Scheelje, L., Schindler, S., Schreiner, N. B., Schreiter, M. L., Seida, C., Shanks, D. R., Siems, M.-C., Stitz, M., Starkulla, M., Stäglich, M., Thies, K., Thum, E., Undorf, M., Unger, B. D., Urlichich, D., Vadillo, M. A., Wackershauser-Sablotny, V., Wagner, F. S., Wessel, I., Wolf, H., Zhou, A., Zimdahl, M., &amp; Schütz, A. (2022). OpAQ: Open Anchoring Quest, Version 1.1.42.94. <a href="https://dx.doi.org/10.17605/OSF.IO/YGNVB" class="uri">https://dx.doi.org/10.17605/OSF.IO/YGNVB</a>. Available online at <a href="https://metaanalyses.shinyapps.io/OpAQ/" class="uri">https://metaanalyses.shinyapps.io/OpAQ/</a>.</p></li>
<li><p><strong>Röseler, L.</strong>, Adler, S., Schöniger, M. (2022). A Toolbox to Identify P-Hacking. Version 0.0.5. Available online at <a href="https://metaanalyses.shinyapps.io/toolbox/" class="uri">https://metaanalyses.shinyapps.io/toolbox/</a>.</p></li>
<li><p><strong>Röseler, L.</strong>, Körner, R., &amp; Schütz, A. (2021). Dynamic Meta-Analysis of Body Position Effects ShinyApp. Available online at <a href="https://metaanalyses.shinyapps.io/bodypositions/" class="uri">https://metaanalyses.shinyapps.io/bodypositions/</a>.</p></li>
<li><p><strong>Röseler, L.</strong>, Röseler, J. J. (2020). Studienfeedback ShinyApp. Available online at <a href="https://l-air.shinyapps.io/feedback/" class="uri">https://l-air.shinyapps.io/feedback/</a>.</p></li>
</ul>
</section>
<section id="research-proposals" class="level1">
<h1>Research proposals</h1>
<p>This is a selection of research proposals that I created alone or together with other researchers.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Proposal</th>
<th>Role</th>
<th>Program and Funder</th>
<th>Link</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Moderators of Anchoring Effects</td>
<td>First author</td>
<td>DFG, Sachbeihilfe</td>
<td><a href="https://osf.io/x6bqh/" class="uri">https://osf.io/x6bqh/</a></td>
<td>rejected</td>
</tr>
<tr class="even">
<td>Formation of a Replication Journal</td>
<td>First author</td>
<td>Topical Program, University of Münster</td>
<td><a href="https://osf.io/9vgx7/" class="uri">https://osf.io/9vgx7/</a></td>
<td>under review</td>
</tr>
<tr class="odd">
<td>Expanding the Replication Database</td>
<td>First author</td>
<td>Ideenlabor, University of Münster</td>
<td><a href="https://osf.io/854vt/" class="uri">https://osf.io/854vt/</a></td>
<td>rejected</td>
</tr>
<tr class="even">
<td>Expanding the FORRT Replication Database</td>
<td>Second author</td>
<td>DFG, Meta-REP Priority Program</td>
<td><hr></td>
<td>rejected</td>
</tr>
</tbody>
</table>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2024, Lukas Röseler</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a> and <a href="https://github.com/jtr13/website-template">Joyce Robbins’ website template</a>.</p>
</div>
  </div>
</footer>




</body></html>